import { z } from "zod";

import { getContrastRatio, mixHexColors, normalizeHexColor } from "./colors";

const hexColor = z.string().transform((value, ctx) => {
  const color = normalizeHexColor(value);
  if (!color) {
    ctx.addIssue({ code: "custom", message: "Use a valid HEX color" });
    return z.NEVER;
  }
  return color;
});

/** AI and manual color input share this four-color contract. */
export const organizationThemeSeedsSchema = z.object({
  primary: hexColor,
  secondary: hexColor,
  accent: hexColor,
  destructive: hexColor,
});

export const organizationThemeSchema = organizationThemeSeedsSchema.extend({
  version: z.literal(2),
  darkBrightness: z.number().int().min(0).max(100).default(35),
  density: z
    .enum(["compact", "comfortable", "spacious"])
    .default("comfortable"),
  font: z
    .enum(["geist", "inter", "poppins", "merriweather", "jetbrains"])
    .default("geist"),
  radius: z.enum(["none", "small", "large"]).default("large"),
  shadow: z
    .object({
      x: z.number().int().min(-12).max(12),
      y: z.number().int().min(-12).max(24),
      blur: z.number().int().min(0).max(48),
      spread: z.number().int().min(-12).max(16),
      opacity: z.number().int().min(0).max(40),
    })
    .default({ x: 0, y: 4, blur: 12, spread: -2, opacity: 14 }),
  size: z.enum(["small", "default", "large"]).default("default"),
});

export type OrganizationTheme = z.infer<typeof organizationThemeSchema>;
export type OrganizationThemeDraft = z.input<
  typeof organizationThemeSeedsSchema
>;

export const DEFAULT_ORGANIZATION_THEME: OrganizationTheme =
  organizationThemeSchema.parse({
    version: 2,
    primary: "#27272A",
    secondary: "#71717A",
    accent: "#52525B",
    destructive: "#DC2626",
  });

/** Store only versioned seeds. Layout choices are never generated by AI. */
export function normalizeOrganizationTheme(value: OrganizationThemeDraft) {
  const seeds = organizationThemeSeedsSchema.parse(value);
  const red = Number.parseInt(seeds.destructive.slice(1, 3), 16);
  const green = Number.parseInt(seeds.destructive.slice(3, 5), 16);
  const blue = Number.parseInt(seeds.destructive.slice(5, 7), 16);
  const chroma = red - Math.min(green, blue);
  const hue = chroma > 0 ? (60 * (green - blue)) / chroma : 0;
  // Keep danger colors in the red hue range, with enough saturation to be recognizable.
  if (!(red >= 120 && chroma >= 60 && hue >= -15 && hue <= 20)) {
    seeds.destructive = DEFAULT_ORGANIZATION_THEME.destructive;
  }
  return { version: 2 as const, ...seeds };
}

const legacyThemeSchema = z.object({
  primary: hexColor,
  background: hexColor,
  foreground: hexColor,
  secondary: hexColor.optional(),
  accent: hexColor.optional(),
  destructive: hexColor.optional(),
});

/** Upgrade old persisted themes at the read seam; never retain AI surface overrides. */
export function parseOrganizationTheme(
  value: unknown,
): OrganizationTheme | null {
  if (!value || typeof value !== "object") return null;
  if ("version" in value) {
    const parsed = organizationThemeSchema.safeParse(value);
    if (!parsed.success) return null;
    return { ...parsed.data, ...normalizeOrganizationTheme(parsed.data) };
  }
  const legacy = legacyThemeSchema.safeParse(value);
  if (!legacy.success) return null;
  return organizationThemeSchema.parse(
    normalizeOrganizationTheme({
      primary: legacy.data.primary,
      secondary: legacy.data.secondary ?? legacy.data.primary,
      accent: legacy.data.accent ?? legacy.data.primary,
      destructive:
        legacy.data.destructive ?? DEFAULT_ORGANIZATION_THEME.destructive,
    }),
  );
}

function mix(first: string, second: string, amount: number) {
  return mixHexColors(first, second, amount)!;
}

function readable(surface: string) {
  return getContrastRatio(surface, "#000000") >=
    getContrastRatio(surface, "#FFFFFF")
    ? "#000000"
    : "#FFFFFF";
}

/** Bounded contrast correction preserves the seed until adjustment is necessary. */
function contrast(color: string, surface: string, minimum: number) {
  if (getContrastRatio(color, surface) >= minimum) return color;
  const target = readable(surface);
  for (let step = 1; step <= 100; step++) {
    const candidate = mix(color, target, step / 100);
    if (getContrastRatio(candidate, surface) >= minimum) return candidate;
  }
  return target;
}

function contrastAgainstAll(
  color: string,
  surfaces: string[],
  minimum: number,
) {
  if (
    surfaces.every((surface) => getContrastRatio(color, surface) >= minimum)
  ) {
    return color;
  }
  const score = (candidate: string) =>
    Math.min(
      ...surfaces.map((surface) => getContrastRatio(candidate, surface)),
    );
  const target = score("#000000") >= score("#FFFFFF") ? "#000000" : "#FFFFFF";
  for (let step = 1; step <= 100; step++) {
    const candidate = mix(color, target, step / 100);
    if (
      surfaces.every(
        (surface) => getContrastRatio(candidate, surface) >= minimum,
      )
    ) {
      return candidate;
    }
  }
  return target;
}

/** Complete semantic tokens; both platform adapters only rename these values. */
export function createOrganizationThemeTokens(
  theme: OrganizationTheme,
  mode: "light" | "dark",
) {
  const dark = mode === "dark";
  const neutral = dark
    ? mix("#09090B", "#242428", theme.darkBrightness / 100)
    : "#FFFFFF";
  const background = mix(neutral, theme.primary, dark ? 0.025 : 0.015);
  const foreground = dark ? "#FAFAFA" : "#18181B";
  const cardBase = dark ? mix(background, "#FFFFFF", 0.04) : "#FFFFFF";
  const card = mix(cardBase, theme.primary, dark ? 0.06 : 0.055);
  const popover = mix(card, theme.primary, dark ? 0.045 : 0.025);
  const muted = mix(background, foreground, dark ? 0.09 : 0.055);
  const sidebar = mix(background, theme.primary, dark ? 0.055 : 0.04);
  const secondary = mix(card, theme.secondary, dark ? 0.19 : 0.12);
  const accent = mix(card, theme.accent, dark ? 0.24 : 0.16);
  const primary = contrast(contrast(theme.primary, background, 4.5), card, 4.5);
  const destructive = contrast(theme.destructive, background, 4.5);
  const border = mix(background, foreground, dark ? 0.22 : 0.18);
  const mutedForeground = contrastAgainstAll(
    mix(background, foreground, 0.6),
    [muted, card],
    4.5,
  );
  const chart = (seed: string) => contrast(seed, card, 3);
  const candidates = [
    theme.primary,
    theme.secondary,
    theme.accent,
    ...["#D97706", "#0891B2", "#7C3AED", "#059669", "#DB2777", "#2563EB"].map(
      (color) => mix(color, theme.primary, 0.15),
    ),
  ].map(chart);
  const charts: string[] = [];
  const distance = (a: string, b: string) =>
    [1, 3, 5].reduce(
      (sum, start) =>
        sum +
        (Number.parseInt(a.slice(start, start + 2), 16) -
          Number.parseInt(b.slice(start, start + 2), 16)) **
          2,
      0,
    );
  // If brand seeds coincide, choose the most distinct deterministic alternative.
  for (let index = 0; index < 5; index++) {
    const preferred = candidates[index]!;
    const separation = (color: string) =>
      Math.min(...charts.map((previous) => distance(color, previous)));
    charts.push(
      separation(preferred) >= 8100
        ? preferred
        : candidates.reduce((best, color) =>
            separation(color) > separation(best) ? color : best,
          ),
    );
  }

  const highlightPair = (seed: string) => {
    const background = mix(card, seed, dark ? 0.24 : 0.13);
    return {
      text: contrast(seed, background, 4.5),
      background,
    };
  };
  const highlightGray = highlightPair(
    mix(theme.secondary, foreground, dark ? 0.55 : 0.45),
  );
  const highlightBrown = highlightPair(mix("#92400E", theme.secondary, 0.15));
  const highlightRed = highlightPair(destructive);
  const highlightOrange = highlightPair(mix("#C2410C", theme.accent, 0.15));
  const highlightYellow = highlightPair(mix("#A16207", theme.accent, 0.15));
  const highlightGreen = highlightPair(mix("#15803D", theme.secondary, 0.15));
  const highlightBlue = highlightPair(mix("#1D4ED8", theme.primary, 0.15));
  const highlightPurple = highlightPair(mix("#7E22CE", theme.accent, 0.15));
  const highlightPink = highlightPair(mix("#BE185D", theme.accent, 0.15));

  return {
    background,
    foreground,
    card,
    cardForeground: foreground,
    popover,
    popoverForeground: foreground,
    primary,
    primaryForeground: readable(primary),
    secondary,
    secondaryForeground: contrast(foreground, secondary, 4.5),
    muted,
    mutedForeground,
    accent,
    accentForeground: contrast(foreground, accent, 4.5),
    destructive,
    destructiveForeground: readable(destructive),
    border,
    input: contrast(border, card, 3),
    ring: contrast(primary, card, 3),
    chart1: charts[0]!,
    chart2: charts[1]!,
    chart3: charts[2]!,
    chart4: charts[3]!,
    chart5: charts[4]!,
    sidebar,
    sidebarForeground: foreground,
    sidebarPrimary: primary,
    sidebarPrimaryForeground: readable(primary),
    sidebarAccent: accent,
    sidebarAccentForeground: contrast(foreground, accent, 4.5),
    sidebarBorder: mix(sidebar, foreground, 0.2),
    sidebarRing: contrast(primary, sidebar, 3),
    highlightGrayText: highlightGray.text,
    highlightGrayBackground: highlightGray.background,
    highlightBrownText: highlightBrown.text,
    highlightBrownBackground: highlightBrown.background,
    highlightRedText: highlightRed.text,
    highlightRedBackground: highlightRed.background,
    highlightOrangeText: highlightOrange.text,
    highlightOrangeBackground: highlightOrange.background,
    highlightYellowText: highlightYellow.text,
    highlightYellowBackground: highlightYellow.background,
    highlightGreenText: highlightGreen.text,
    highlightGreenBackground: highlightGreen.background,
    highlightBlueText: highlightBlue.text,
    highlightBlueBackground: highlightBlue.background,
    highlightPurpleText: highlightPurple.text,
    highlightPurpleBackground: highlightPurple.background,
    highlightPinkText: highlightPink.text,
    highlightPinkBackground: highlightPink.background,
  };
}

export type OrganizationThemeTokens = ReturnType<
  typeof createOrganizationThemeTokens
>;
