export const themeColors = {
  light: {
    background: "#ffffff",
    foreground: "#0a0a0a",
    card: "#ffffff",
    cardForeground: "#0a0a0a",
    popover: "#ffffff",
    popoverForeground: "#0a0a0a",
    primary: "#171717",
    primaryForeground: "#fafafa",
    secondary: "#f5f5f5",
    secondaryForeground: "#171717",
    muted: "#f5f5f5",
    mutedForeground: "#737373",
    accent: "#f5f5f5",
    accentForeground: "#171717",
    destructive: "#e7000b",
    border: "#e5e5e5",
    input: "#e5e5e5",
    ring: "#a1a1a1",
    chart1: "#d4d4d4",
    chart2: "#737373",
    chart3: "#525252",
    chart4: "#404040",
    chart5: "#262626",
    sidebar: "#fafafa",
    sidebarForeground: "#0a0a0a",
    sidebarPrimary: "#171717",
    sidebarPrimaryForeground: "#fafafa",
    sidebarAccent: "#f5f5f5",
    sidebarAccentForeground: "#171717",
    sidebarBorder: "#e5e5e5",
    sidebarRing: "#a1a1a1",
  },
  dark: {
    background: "#0a0a0a",
    foreground: "#fafafa",
    card: "#171717",
    cardForeground: "#fafafa",
    popover: "#171717",
    popoverForeground: "#fafafa",
    primary: "#e5e5e5",
    primaryForeground: "#171717",
    secondary: "#262626",
    secondaryForeground: "#fafafa",
    muted: "#262626",
    mutedForeground: "#a1a1a1",
    accent: "#262626",
    accentForeground: "#fafafa",
    destructive: "#ff6467",
    border: "rgba(255, 255, 255, 0.1)",
    input: "rgba(255, 255, 255, 0.15)",
    ring: "#737373",
    chart1: "#d4d4d4",
    chart2: "#737373",
    chart3: "#525252",
    chart4: "#404040",
    chart5: "#262626",
    sidebar: "#171717",
    sidebarForeground: "#fafafa",
    sidebarPrimary: "#1447e6",
    sidebarPrimaryForeground: "#fafafa",
    sidebarAccent: "#262626",
    sidebarAccentForeground: "#fafafa",
    sidebarBorder: "rgba(255, 255, 255, 0.1)",
    sidebarRing: "#737373",
  },
} as const;

export type ColorScheme = keyof typeof themeColors;
export type ThemeColors = (typeof themeColors)[ColorScheme];

const variableNames = {
  background: "--color-background",
  foreground: "--color-foreground",
  card: "--color-card",
  cardForeground: "--color-card-foreground",
  popover: "--color-popover",
  popoverForeground: "--color-popover-foreground",
  primary: "--color-primary",
  primaryForeground: "--color-primary-foreground",
  secondary: "--color-secondary",
  secondaryForeground: "--color-secondary-foreground",
  muted: "--color-muted",
  mutedForeground: "--color-muted-foreground",
  accent: "--color-accent",
  accentForeground: "--color-accent-foreground",
  destructive: "--color-destructive",
  border: "--color-border",
  input: "--color-input",
  ring: "--color-ring",
  chart1: "--color-chart-1",
  chart2: "--color-chart-2",
  chart3: "--color-chart-3",
  chart4: "--color-chart-4",
  chart5: "--color-chart-5",
  sidebar: "--color-sidebar",
  sidebarForeground: "--color-sidebar-foreground",
  sidebarPrimary: "--color-sidebar-primary",
  sidebarPrimaryForeground: "--color-sidebar-primary-foreground",
  sidebarAccent: "--color-sidebar-accent",
  sidebarAccentForeground: "--color-sidebar-accent-foreground",
  sidebarBorder: "--color-sidebar-border",
  sidebarRing: "--color-sidebar-ring",
} as const;

function createThemeVariables(colors: ThemeColors) {
  return Object.fromEntries(
    Object.entries(variableNames).map(([name, variable]) => [
      variable,
      colors[name as keyof ThemeColors],
    ]),
  ) as Record<`--${string}`, string>;
}

export const themeVariables = {
  light: createThemeVariables(themeColors.light),
  dark: createThemeVariables(themeColors.dark),
} as const;
