"use client";

import { useRef, useState, type ChangeEvent } from "react";
import { createReactBlockSpec } from "@blocknote/react";
import {
  BookOpenIcon,
  ImageIcon,
  LoaderCircleIcon,
  MessageCircleIcon,
  PaletteIcon,
  UploadIcon,
} from "lucide-react";
import { toast } from "sonner";

import {
  lessonPageBlockType,
  lessonPageDefaults,
  lessonPageThemes,
} from "~/lib/blocknote/block-catalog";

import { useEditorAssetUpload } from "../asset-upload-context";
import { AssetUrl } from "./asset-media-block";
import { CustomBlockToolbar } from "./custom-block-toolbar";
import { EditableBlockText as EditableText } from "./editable-block-text";

const lessonPageThemeStyles = {
  rose: {
    label: "Rose",
    accent: "var(--primary)",
  },
  ocean: {
    label: "Ocean",
    accent: "var(--chart-1)",
  },
  forest: {
    label: "Forest",
    accent: "var(--chart-2)",
  },
  sunset: {
    label: "Sunset",
    accent: "var(--destructive)",
  },
} as const;

const lessonPageProps = {
  theme: { default: "rose", values: [...lessonPageThemes] },
  assetId: { default: "" },
  fileName: { default: "" },
  contentType: { default: "" },
  eyebrow: { default: lessonPageDefaults.eyebrow },
  chapterNumber: { default: lessonPageDefaults.chapterNumber },
  title: { default: lessonPageDefaults.title },
  subtitle: { default: lessonPageDefaults.subtitle },
  question: { default: lessonPageDefaults.question },
  answer: { default: lessonPageDefaults.answer },
  grammarLabel: { default: lessonPageDefaults.grammarLabel },
  grammarTitle: { default: lessonPageDefaults.grammarTitle },
  grammarDescription: { default: lessonPageDefaults.grammarDescription },
  vocabularyLabel: { default: lessonPageDefaults.vocabularyLabel },
  vocabularyTitle: { default: lessonPageDefaults.vocabularyTitle },
  vocabularyDescription: {
    default: lessonPageDefaults.vocabularyDescription,
  },
  cultureLabel: { default: lessonPageDefaults.cultureLabel },
  cultureTitle: { default: lessonPageDefaults.cultureTitle },
  cultureDescription: { default: lessonPageDefaults.cultureDescription },
  objectivesLabel: { default: lessonPageDefaults.objectivesLabel },
  objectiveOne: { default: lessonPageDefaults.objectiveOne },
  objectiveTwo: { default: lessonPageDefaults.objectiveTwo },
};

const emptyLessonPageProps = {
  theme: "rose",
  assetId: "",
  fileName: "",
  contentType: "",
  eyebrow: "",
  chapterNumber: "",
  title: "",
  subtitle: "",
  question: "",
  answer: "",
  grammarLabel: "",
  grammarTitle: "",
  grammarDescription: "",
  vocabularyLabel: "",
  vocabularyTitle: "",
  vocabularyDescription: "",
  cultureLabel: "",
  cultureTitle: "",
  cultureDescription: "",
  objectivesLabel: "",
  objectiveOne: "",
  objectiveTwo: "",
} as const;

function LessonHeroImage({
  assetId,
  editable,
  fileName,
  onUploaded,
  title,
}: {
  assetId: string;
  editable: boolean;
  fileName: string;
  onUploaded: (asset: {
    assetId: string;
    fileName: string;
    contentType: string;
  }) => void;
  title: string;
}) {
  const inputRef = useRef<HTMLInputElement>(null);
  const upload = useEditorAssetUpload();
  const [uploading, setUploading] = useState(false);

  async function selectFile(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    event.target.value = "";
    if (!file || !upload) return;
    setUploading(true);
    try {
      onUploaded(await upload.upload(file, "image"));
      toast.success("Gambar lesson page diperbarui.");
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : "Upload gambar gagal.",
      );
    } finally {
      setUploading(false);
    }
  }

  return (
    <div className="group bg-muted ring-foreground/10 relative aspect-[16/9] overflow-hidden rounded-xl ring-1">
      <input
        ref={inputRef}
        accept="image/*"
        className="hidden"
        onChange={(event) => void selectFile(event)}
        type="file"
      />
      {assetId ? (
        <AssetUrl assetId={assetId}>
          {(url, loading) =>
            loading ? (
              <div className="text-muted-foreground flex size-full items-center justify-center gap-2 text-sm">
                <LoaderCircleIcon className="size-5 animate-spin" /> Memuat
                gambar
              </div>
            ) : url ? (
              // Asset URLs are generated by the authenticated storage API.
              // eslint-disable-next-line @next/next/no-img-element
              <img
                alt={title || fileName || "Lesson cover"}
                className="size-full object-cover"
                src={url}
              />
            ) : (
              <div className="text-muted-foreground flex size-full items-center justify-center text-sm">
                Gambar tidak tersedia.
              </div>
            )
          }
        </AssetUrl>
      ) : (
        <div className="text-muted-foreground bg-muted/50 flex size-full flex-col items-center justify-center gap-3 p-6 text-center">
          <div className="bg-background ring-foreground/10 rounded-lg p-3 ring-1">
            <ImageIcon className="size-8" />
          </div>
          <p className="max-w-sm text-sm">
            Tambahkan foto yang memberi konteks visual untuk pelajaran ini.
          </p>
        </div>
      )}

      {editable ? (
        upload ? (
          <button
            className="bg-foreground text-background absolute right-3 bottom-3 inline-flex h-9 items-center gap-2 rounded-lg px-3 text-sm font-medium shadow-sm transition hover:opacity-90 disabled:opacity-60"
            disabled={uploading}
            onClick={() => inputRef.current?.click()}
            type="button"
          >
            {uploading ? (
              <LoaderCircleIcon className="size-4 animate-spin" />
            ) : (
              <UploadIcon className="size-4" />
            )}
            {assetId ? "Ganti gambar" : "Unggah gambar"}
          </button>
        ) : (
          <div className="bg-background/90 text-muted-foreground ring-foreground/10 absolute right-3 bottom-3 rounded-md px-2.5 py-1.5 text-xs font-medium ring-1 backdrop-blur">
            Upload tidak tersedia
          </div>
        )
      ) : null}
    </div>
  );
}

function LearningCard({
  accent,
  description,
  editable,
  label,
  onDescriptionChange,
  onLabelChange,
  onTitleChange,
  title,
}: {
  accent: string;
  description: string;
  editable: boolean;
  label: string;
  onDescriptionChange: (value: string) => void;
  onLabelChange: (value: string) => void;
  onTitleChange: (value: string) => void;
  title: string;
}) {
  return (
    <div className="bg-muted/35 ring-foreground/10 min-w-0 rounded-lg p-4 ring-1">
      <div className="mb-4 flex min-w-0 items-start gap-2.5">
        <span
          aria-hidden="true"
          className="mt-1 h-5 w-1 shrink-0 rounded-full"
          style={{ backgroundColor: accent }}
        />
        <EditableText
          ariaLabel="Label fokus pelajaran"
          className="w-full text-xs font-semibold tracking-[0.12em] uppercase"
          editable={editable}
          onChange={onLabelChange}
          value={label}
        />
      </div>
      <EditableText
        ariaLabel="Judul fokus pelajaran"
        className="text-foreground w-full text-base leading-snug font-medium"
        editable={editable}
        onChange={onTitleChange}
        value={title}
      />
      <EditableText
        ariaLabel="Deskripsi fokus pelajaran"
        className="text-muted-foreground mt-1.5 w-full text-sm leading-relaxed"
        editable={editable}
        onChange={onDescriptionChange}
        value={description}
      />
    </div>
  );
}

export const lessonPageBlock = createReactBlockSpec(
  {
    type: lessonPageBlockType,
    propSchema: lessonPageProps,
    content: "none",
  },
  {
    render: ({ block, editor }) => {
      const scheme = lessonPageThemeStyles[block.props.theme];
      const editable = editor.isEditable;

      return (
        <article
          className="text-foreground my-4 w-full min-w-0 bg-transparent"
          contentEditable={false}
          data-custom-block
        >
          {editable ? (
            <div className="border-border bg-muted/40 flex items-center justify-between gap-3 border-b px-4 py-2.5">
              <div className="text-muted-foreground flex items-center gap-2 text-xs font-semibold tracking-wide uppercase">
                <PaletteIcon className="size-3.5" /> Palet
              </div>
              <div className="flex items-center gap-2">
                <div className="flex items-center gap-1.5">
                  {lessonPageThemes.map((theme) => {
                    const option = lessonPageThemeStyles[theme];
                    const selected = block.props.theme === theme;
                    return (
                      <button
                        aria-label={`Gunakan palet ${option.label}`}
                        aria-pressed={selected}
                        className={`ring-foreground/10 focus-visible:ring-ring grid size-7 place-items-center rounded-md ring-1 transition focus-visible:ring-2 focus-visible:outline-none ${selected ? "bg-background shadow-xs" : "hover:bg-background/70"}`}
                        key={theme}
                        onClick={() =>
                          editor.updateBlock(block, { props: { theme } })
                        }
                        title={option.label}
                        type="button"
                      >
                        <span
                          className="size-3.5 rounded-full"
                          style={{ backgroundColor: option.accent }}
                        />
                      </button>
                    );
                  })}
                </div>
                <CustomBlockToolbar
                  block={block}
                  editable={editable}
                  onClear={() =>
                    editor.updateBlock(block, {
                      props: emptyLessonPageProps,
                    })
                  }
                />
              </div>
            </div>
          ) : null}

          <header className="relative min-w-0 p-4 sm:p-6">
            <span
              aria-hidden="true"
              className="absolute top-6 bottom-6 left-0 w-1 rounded-r-full"
              style={{ backgroundColor: scheme.accent }}
            />
            <div className="grid min-w-0 gap-4 sm:grid-cols-[8.5rem_minmax(0,1fr)] sm:items-center sm:gap-6">
              <div className="bg-muted/50 ring-foreground/10 min-w-0 rounded-lg p-4 text-left ring-1 sm:text-center">
                <EditableText
                  ariaLabel="Label seri"
                  className="w-full text-xs font-semibold tracking-[0.16em] uppercase"
                  editable={editable}
                  onChange={(eyebrow) =>
                    editor.updateBlock(block, { props: { eyebrow } })
                  }
                  value={block.props.eyebrow}
                />
                <EditableText
                  ariaLabel="Nomor bab"
                  className="text-foreground mt-2 w-full text-4xl leading-none font-medium tracking-tight sm:text-center sm:text-5xl"
                  editable={editable}
                  onChange={(chapterNumber) =>
                    editor.updateBlock(block, { props: { chapterNumber } })
                  }
                  value={block.props.chapterNumber}
                />
              </div>
              <div className="min-w-0">
                <EditableText
                  ariaLabel="Judul lesson page"
                  className="text-foreground w-full text-2xl leading-tight font-medium tracking-tight sm:text-3xl"
                  editable={editable}
                  onChange={(title) =>
                    editor.updateBlock(block, { props: { title } })
                  }
                  value={block.props.title}
                />
                <EditableText
                  ariaLabel="Subjudul lesson page"
                  className="text-muted-foreground mt-1.5 w-full text-sm leading-relaxed sm:text-base"
                  editable={editable}
                  onChange={(subtitle) =>
                    editor.updateBlock(block, { props: { subtitle } })
                  }
                  value={block.props.subtitle}
                />
              </div>
            </div>
          </header>

          <div className="px-4 sm:px-6">
            <LessonHeroImage
              assetId={block.props.assetId}
              editable={editable}
              fileName={block.props.fileName}
              onUploaded={(asset) =>
                editor.updateBlock(block, { props: asset })
              }
              title={block.props.title}
            />
          </div>

          <section className="grid min-w-0 gap-3 px-4 py-5 sm:grid-cols-2 sm:px-6 sm:py-6">
            <div className="bg-muted/35 ring-foreground/10 min-w-0 rounded-lg p-4 ring-1">
              <div
                className="mb-2 flex items-center gap-2 text-xs font-semibold tracking-[0.12em] uppercase"
                style={{ color: scheme.accent }}
              >
                <MessageCircleIcon className="size-3.5" /> Contoh pertanyaan
              </div>
              <EditableText
                ariaLabel="Pertanyaan contoh"
                className="text-foreground w-full text-sm leading-relaxed font-medium"
                editable={editable}
                onChange={(question) =>
                  editor.updateBlock(block, { props: { question } })
                }
                value={block.props.question}
              />
            </div>
            <div
              className="bg-muted/35 ring-foreground/10 min-w-0 rounded-lg border-l-2 p-4 ring-1"
              style={{ borderLeftColor: scheme.accent }}
            >
              <div className="text-muted-foreground mb-2 text-xs font-semibold tracking-[0.12em] uppercase">
                Contoh jawaban
              </div>
              <EditableText
                ariaLabel="Jawaban contoh"
                className="text-foreground w-full text-sm leading-relaxed font-medium"
                editable={editable}
                onChange={(answer) =>
                  editor.updateBlock(block, { props: { answer } })
                }
                value={block.props.answer}
              />
            </div>
          </section>

          <section className="border-border min-w-0 border-t px-4 py-6 sm:px-6">
            <p className="text-muted-foreground mb-4 text-xs font-semibold tracking-[0.14em] uppercase">
              Fokus pelajaran
            </p>
            <div className="grid min-w-0 gap-3 md:grid-cols-3">
              <LearningCard
                accent={scheme.accent}
                description={block.props.grammarDescription}
                editable={editable}
                label={block.props.grammarLabel}
                onDescriptionChange={(grammarDescription) =>
                  editor.updateBlock(block, { props: { grammarDescription } })
                }
                onLabelChange={(grammarLabel) =>
                  editor.updateBlock(block, { props: { grammarLabel } })
                }
                onTitleChange={(grammarTitle) =>
                  editor.updateBlock(block, { props: { grammarTitle } })
                }
                title={block.props.grammarTitle}
              />
              <LearningCard
                accent={scheme.accent}
                description={block.props.vocabularyDescription}
                editable={editable}
                label={block.props.vocabularyLabel}
                onDescriptionChange={(vocabularyDescription) =>
                  editor.updateBlock(block, {
                    props: { vocabularyDescription },
                  })
                }
                onLabelChange={(vocabularyLabel) =>
                  editor.updateBlock(block, { props: { vocabularyLabel } })
                }
                onTitleChange={(vocabularyTitle) =>
                  editor.updateBlock(block, { props: { vocabularyTitle } })
                }
                title={block.props.vocabularyTitle}
              />
              <LearningCard
                accent={scheme.accent}
                description={block.props.cultureDescription}
                editable={editable}
                label={block.props.cultureLabel}
                onDescriptionChange={(cultureDescription) =>
                  editor.updateBlock(block, { props: { cultureDescription } })
                }
                onLabelChange={(cultureLabel) =>
                  editor.updateBlock(block, { props: { cultureLabel } })
                }
                onTitleChange={(cultureTitle) =>
                  editor.updateBlock(block, { props: { cultureTitle } })
                }
                title={block.props.cultureTitle}
              />
            </div>
          </section>

          <section className="border-border bg-muted/20 min-w-0 border-t px-4 py-6 sm:px-6">
            <div className="mb-4 flex min-w-0 items-start gap-3">
              <span
                className="mt-0.5 inline-flex size-8 shrink-0 items-center justify-center rounded-md text-white"
                style={{ backgroundColor: scheme.accent }}
              >
                <BookOpenIcon className="size-4" />
              </span>
              <EditableText
                ariaLabel="Label tujuan belajar"
                className="text-foreground w-full text-sm font-semibold tracking-wide"
                editable={editable}
                onChange={(objectivesLabel) =>
                  editor.updateBlock(block, { props: { objectivesLabel } })
                }
                value={block.props.objectivesLabel}
              />
            </div>
            <div className="bg-card ring-foreground/10 min-w-0 divide-y rounded-lg px-4 ring-1">
              <div className="grid min-w-0 grid-cols-[2rem_minmax(0,1fr)] gap-3 py-3.5">
                <span
                  className="pt-0.5 text-xs font-semibold tabular-nums"
                  style={{ color: scheme.accent }}
                >
                  01
                </span>
                <EditableText
                  ariaLabel="Tujuan belajar pertama"
                  className="text-foreground w-full text-sm leading-relaxed"
                  editable={editable}
                  onChange={(objectiveOne) =>
                    editor.updateBlock(block, { props: { objectiveOne } })
                  }
                  value={block.props.objectiveOne}
                />
              </div>
              <div className="grid min-w-0 grid-cols-[2rem_minmax(0,1fr)] gap-3 py-3.5">
                <span
                  className="pt-0.5 text-xs font-semibold tabular-nums"
                  style={{ color: scheme.accent }}
                >
                  02
                </span>
                <EditableText
                  ariaLabel="Tujuan belajar kedua"
                  className="text-foreground w-full text-sm leading-relaxed"
                  editable={editable}
                  onChange={(objectiveTwo) =>
                    editor.updateBlock(block, { props: { objectiveTwo } })
                  }
                  value={block.props.objectiveTwo}
                />
              </div>
            </div>
          </section>
        </article>
      );
    },
  },
)();
